apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: toki-iam
  name: toki-iam
spec:
  replicas: 1
  selector:
    matchLabels:
      run: toki-iam
  strategy: {}
  template:
    metadata:
      labels:
        run: toki-iam
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - sleep 3600
        image: amazon/aws-cli
        name: toki-iam
        resources: {}
      serviceAccountName: toki-sa